import { createInsertSchema } from "drizzle-zod";

import { examples } from "@/db/schema";

export const createExampleSchema = createInsertSchema(examples);

// Type derived from insert schema - id and createdAt are auto-generated by DB, only name is required
export type TCreateExampleInput = { name: string };
